* Basics
After patching, run:
#+begin_src bash
sudo make clean install
#+end_src

Then restart dwm, st, etc. for patches to go through

** .xinitrc
If using ly login manager, just use the =.xinitrc= option. If you use some =.desktop= file under =/usr/share/xsessions/dwm.desktop= and have to make autostart files under =.config/autostart/something.desktop=. Too complicated. Just use the .xinitrc option and everything works!

Current =.xinitrc=:
#+begin_src bash
#!/bin/sh
setxkbmap -option caps:super
xcape -e "Super_L=Escape"
slstatus &
nitrogen --restore --set-zoom-fill &
picom -b &
exec dwm
#+end_src

* Suckless Configs
** Keybindings
I use capslock as an additional escape because it is easier to reach than the super key and some of my older keyboards don't have a super key. 

However, I also use capslock as an additional super because I like vim keybindings and esc is too far to reach.

To do this, first set capslock as an additional SUPER. Ensure that this is set before the xcape command, otherwise only the left super will be set to ESC without the tap behavior for caps lock:
#+begin_src bash
setxkbmap -option caps:super
#+end_src

Now, use xcape to set capslock to be super when held, esc when tapped.
#+begin_src bash
sudo apt install xcape
xcape -e "Super_L=Escape"
#+end_src

Now instead of running these commands manually, put them in =.xinitrc=:
#+begin_src bash
#!/bin/sh
setxkbmap -option caps:super
xcape -e "Super_L=Escape"
slstatus &
nitrogen --restore --set-zoom-fill &
picom -b &
exec dwm
#+end_src

Make sure the =setxkbmap= and =xcape= run sequentially, otherwise the order will be wrong due to racing condition of the two configurations.

if not using a login manager, must start using .xinitrc or .xsession
- remember to install autorandr and nitrogen for backgrounds

** Install Flameshot for Screenshot
#+begin_src bash
# ubuntu/debian
sudo apt-get install flameshot 
#+end_src

** Blueman bluetooth management
Check if your computer has a bluetooth adapter, if not, buy a USB bluetooth adapter.

To use it, install [[https://wiki.archlinux.org/title/Blueman][Blueman]]: 
#+begin_src bash
sudo apt-get install blueman
#+end_src

Start it with:
#+begin_src bash
blueman-applet
#+end_src

Launch the GUI with:
#+begin_src bash
blueman-manager
#+end_src

** Powerline Fonts
Install powerline fonts with ([[https://www.fosslinux.com/134427/how-to-install-and-use-powerline-fonts-on-ubuntu.htm][reference]]): 
#+begin_src bash
# ubuntu/debian
sudo apt-get install fonts-powerline

git clone https://github.com/powerline/fonts.git --depth=1
cd fonts
./install.sh
#+end_src


** ST Bug
st issue. If no correct fonts, will just crash st. This is documented in [[https://github.com/LukeSmithxyz/st/issues/130][this issue]]. Thus fix by running/installing this font:
#+begin_src bash
# ubuntu/debian
sudo apt install unifont

# arch
sudo pacman -S bdf-unifont
#+end_src

** dmenu
if dmenu items not showing up but running, the cache maybe malformed. Therefore clear it and restart/rerun dmenu and it should work.

There are two locations where the cache could be:
#+begin_src bash
rm ~/.dmenu_cache
rm ~/.cache/dmenu_run.
#+end_src

** .bash_profile
check if login/non-interactive shell
#+begin_src bash
if [ -n "$BASH_VERSION" ]; then
        if [ -f ~/.bashrc ]; then
        . "$HOME/.bashrc";
        slstatus &
        nitrogen --restore --set-zoom-fill &
        # autorandr --change
        fi
fi
. "$HOME/.cargo/env"
#+end_src
